kind: Module
description: Docker registry for in-cluster builds
name: docker-registry
type: helm
chart: stable/docker-registry
releaseName: garden-docker-registry
version: 1.8.3
values:
  # This is to avoid a multi-attach error when updating
  updateStrategy:
    type: Recreate
  resources:
    limits:
      cpu: ${var.registry-limits-cpu}
      memory: ${var.registry-limits-memory}
    requests:
      cpu: ${var.registry-requests-cpu}
      memory: ${var.registry-requests-memory}
  # Note: this secret doesn't actually matter for security since the registry isn't exposed
  secrets:
    haSharedSecret: "TDVGTm45dVpCMXptOEJGMA=="
  service:
    port: 5000
  persistence:
    enabled: true
    size: ${var.registry-storage-size}
    storageClass: ${var.registry-storage-class}
    deleteEnabled: true
  tolerations:
    - key: "garden-system"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
