apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "garden-build-sync.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "garden-build-sync.name" . }}
    helm.sh/chart: {{ include "garden-build-sync.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "garden-build-sync.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "garden-build-sync.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: garden-build-sync
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
      initContainers:
        - name: init
          image: "busybox:1.31.1"
          command: ["mkdir", "-p", "/data/tmp"]
          volumeMounts:
            - mountPath: /data
              name: garden-build-sync
      containers:
        - name: sync
          image: "gardendev/rsync:0.2.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: rsync
              containerPort: 873
              protocol: TCP
          readinessProbe:
            exec:
              command: [pidof, rsync]
            initialDelaySeconds: 5
            periodSeconds: 2
          livenessProbe:
            exec:
              command: [pidof, rsync]
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - mountPath: /data
              name: garden-build-sync
          env:
            # The service is not exposed at all outside the cluster, so this should be all good.
            - name: ALLOW
              value: "0.0.0.0/0"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- . | nindent 8 }}
    {{- end }}
